#!/usr/bin/env python
"""
One-command script to reproduce all results from the paper:
"Explainable AI for Student Success: A Multi-Objective Framework with SHAP-Based Personalized Recommendations"

This script runs the complete pipeline to generate all tables and figures from the manuscript.

Usage:
    python reproduce_paper.py

This will:
1. Preprocess the data and engineer features
2. Run hyperparameter tuning with Optuna
3. Train all 7 models (LR, RF, SVM, XGBoost, TabNet, FT-Transformer, SAINT)
4. Compute SHAP values and generate explanations
5. Create personalized recommendations
6. Generate all visualizations
7. Reproduce all tables from the manuscript
8. Save fold indices and best hyperparameters for reproducibility

Output:
    results/
    ├── models/           # Trained models
    ├── shap/            # SHAP values and importance
    ├── tables/          # All manuscript tables
    ├── plots/           # All manuscript figures
    ├── folds/           # Exact CV fold indices
    └── hyperparameters/ # Best Optuna parameters
"""

import os
import sys
import json
import logging
from pathlib import Path

# Add src to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.pipeline import main as run_pipeline
from src.config import RESULTS_DIR, RANDOM_SEED, N_FOLDS
from sklearn.model_selection import StratifiedKFold
import numpy as np

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def save_fold_indices():
    """Save the exact train/test indices for reproducibility."""
    logger.info("Saving fold indices for reproducibility...")
    
    # Load preprocessed data to get the target arrays
    from src.data.loader import load_preprocessed_data
    _, y_cgpa, y_at_risk, y_career_ready = load_preprocessed_data()
    
    # Create fold indices directory
    fold_dir = Path(RESULTS_DIR) / "folds"
    fold_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate and save fold indices for each objective
    cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    
    fold_indices = {}
    for obj_name, y in [("cgpa", y_cgpa), ("at_risk", y_at_risk), ("career_ready", y_career_ready)]:
        fold_indices[obj_name] = []
        for fold_idx, (train_idx, test_idx) in enumerate(cv.split(np.zeros(len(y)), y)):
            fold_indices[obj_name].append({
                "fold": fold_idx,
                "train_indices": train_idx.tolist(),
                "test_indices": test_idx.tolist()
            })
    
    # Save to JSON
    with open(fold_dir / "fold_indices.json", "w") as f:
        json.dump(fold_indices, f, indent=2)
    
    logger.info(f"Fold indices saved to {fold_dir / 'fold_indices.json'}")


def reproduce_all_tables():
    """Reproduce all tables from the manuscript."""
    logger.info("Reproducing all manuscript tables...")
    
    # Import revision code modules
    from src.review_comments.revision.code import (
        replication_tables,
        sota_baselines,
        leakage_ablation,
        causal_psm,
        fairness
    )
    
    # Table 3: Leakage control ablation
    logger.info("Generating Table 3: Leakage control ablation...")
    leakage_ablation.run_leakage_ablation()
    
    # Table 7: ML baseline performance
    logger.info("Generating Table 7: Baseline performance...")
    # This is generated by the main pipeline
    
    # Table 9: SOTA comparison
    logger.info("Generating Table 9: SOTA comparison...")
    sota_baselines.run_sota_comparison()
    
    # Table 10: PSM causal analysis
    logger.info("Generating Table 10: PSM analysis...")
    causal_psm.run_psm_analysis()
    
    # Table A1: Optuna search spaces
    logger.info("Generating Table A1: Optuna search spaces...")
    replication_tables.write_search_spaces()
    
    # Table A2: Best hyperparameters
    logger.info("Generating Table A2: Best hyperparameters...")
    replication_tables.write_best_hyperparams()


def main():
    """Run the complete reproduction pipeline."""
    logger.info("="*80)
    logger.info("REPRODUCING ALL RESULTS FROM THE MANUSCRIPT")
    logger.info("="*80)
    
    # Step 1: Preprocess data
    logger.info("\n[Step 1/8] Preprocessing data and engineering features...")
    run_pipeline(["--stage", "preprocess"])
    
    # Step 2: Save fold indices for reproducibility
    logger.info("\n[Step 2/8] Saving fold indices...")
    save_fold_indices()
    
    # Step 3: Hyperparameter tuning
    logger.info("\n[Step 3/8] Running Optuna hyperparameter tuning...")
    run_pipeline(["--stage", "tune"])
    
    # Step 4: Train baseline models
    logger.info("\n[Step 4/8] Training baseline models (LR, RF, SVM, XGBoost)...")
    run_pipeline(["--stage", "baselines"])
    
    # Step 5: Train deep learning models
    logger.info("\n[Step 5/8] Training deep learning models (TabNet, FT-Transformer, SAINT)...")
    run_pipeline(["--stage", "dlmodels"])
    
    # Step 6: SHAP analysis
    logger.info("\n[Step 6/8] Computing SHAP values and explanations...")
    run_pipeline(["--stage", "shap"])
    
    # Step 7: Generate recommendations
    logger.info("\n[Step 7/8] Generating personalized recommendations...")
    run_pipeline(["--stage", "recommend"])
    
    # Step 8: Create visualizations
    logger.info("\n[Step 8/8] Creating all visualizations...")
    run_pipeline(["--stage", "visualize"])
    
    # Additional: Reproduce all manuscript tables
    logger.info("\n[Additional] Reproducing all manuscript tables...")
    reproduce_all_tables()
    
    logger.info("\n" + "="*80)
    logger.info("REPRODUCTION COMPLETE!")
    logger.info("All results saved to: %s", RESULTS_DIR)
    logger.info("="*80)


if __name__ == "__main__":
    main()
